DROP TABLE IF EXISTS player CASCADE;
DROP TABLE IF EXISTS groupedpositions CASCADE;

create table player (
	squadNumber integer not null,
	name varchar(255) not null,
	position varchar(255) not null,
	joined integer not null,
	contractLength integer not null check (contractLength<=6 AND contractLength>=1),
	contractSigned integer not null,
	age integer not null,
	salary float not null,
	primary key (squadNumber)
);
 
create table  groupedpositions(
	id integer generated by default as identity,
	groupedPosition varchar(255),
	primary key (id)
);

alter table player add constraint UK_8qrhl5wlohdjoko9nrorkdjkp unique (squad_number);
alter table groupedpositions add constraint UK_9ome4qyhbd8a1n39dvjsxjks0 unique (groupPosition);
alter table player add constraint FKdtss7ab4sx4oagfqyacono43a foreign key (fk_id) references pond on delete cascade;